name: Build and test

on:
  push:

  pull_request:
    branches: [ develop ]

  workflow_dispatch:

  repository_dispatch:
    types: [utPLSQL-build,utPLSQL-java-api-build]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test on JDK ${{ matrix.jdk }} with utPLSQL ${{ matrix.utplsql_version }}
    runs-on: ubuntu-latest
    env:
      UTPLSQL_VERSION: ${{matrix.utplsql_version}}
      UTPLSQL_FILE: ${{matrix.utplsql_file}}
      DB_URL: "//localhost:1521/FREEPDB1"
      DB_USER: APP
      DB_PASS: APP

    strategy:
      fail-fast: false
      matrix:
        utplsql_version: ["v3.1.11","v3.1.12","v3.1.13","v3.1.14","develop"]
        utplsql_file: ["utPLSQL"]
        jdk: ['8']
    services:
      oracle:
        image: gvenzl/oracle-free:23-slim-faststart
        env:
          ORACLE_PASSWORD: oracle
          DB_URL: "//localhost:1521/FREEPDB1"
          DB_USER: APP
          DB_PASS: APP
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --name oracle

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: ${{matrix.jdk}}

      - name: Install utplsql
        run:  .github/scripts/install_utplsql.sh

      - name: Install demo project
        run:  .github/scripts/install_demo_project.sh

      - name: Build and Test
        run:  mvn verify appassembler:assemble

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          name: 'Github Actions[bot]'
          icon_url: 'https://octodex.github.com/images/mona-the-rivetertocat.png'
