name: Build and test

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test on JDK ${{ matrix.jdk }} with utPLSQL ${{ matrix.utplsql_version }}
    runs-on: ubuntu-latest
    env:
      UTPLSQL_VERSION: ${{matrix.utplsql_version}}
      UTPLSQL_FILE: ${{matrix.utplsql_file}}
      DB_URL: "//localhost:1521/FREEPDB1"
      DB_USER: APP
      DB_PASS: APP

    strategy:
      fail-fast: false
      matrix:
        utplsql_version: ["v3.2.01","develop"]
        utplsql_file: ["utPLSQL"]
        jdk: ['11', '17', '21', '25']
    services:
      oracle:
        image: gvenzl/oracle-free:23-slim-faststart
        env:
          ORACLE_PASSWORD: oracle
          DB_URL: "//localhost:1521/FREEPDB1"
          DB_USER: APP
          DB_PASS: pass
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --name oracle

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{matrix.jdk}}

      - name: Install utplsql
        run:  .github/scripts/install_utplsql.sh

      - name: Install demo project
        run:  .github/scripts/install_demo_project.sh

      - name: Build and Test
        run:  mvn verify appassembler:assemble
