name: Build and test
on:
  push:
    branches: [ '*' ]

  pull_request:
    branches: [ develop ]

  workflow_dispatch:

  repository_dispatch:
    types: [utPLSQL-build,utPLSQL-java-api-build]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test on JDK ${{ matrix.jdk }} with utPLSQL ${{ matrix.utplsql_version }}
    runs-on: ubuntu-latest
    env:
      ORACLE_VERSION: "gvenzl/oracle-xe:18.4.0-slim"
      UTPLSQL_VERSION: ${{matrix.utplsql_version}}
      UTPLSQL_FILE: ${{matrix.utplsql_file}}
      ORACLE_PASSWORD: oracle
      DB_URL: "127.0.0.1:1521:XE"
      DB_USER: app
      DB_PASS: app

    strategy:
      fail-fast: false
      matrix:
        utplsql_version: ["v3.0.1","v3.0.2","v3.0.3","v3.0.4","v3.1.1","v3.1.2","v3.1.3","v3.1.6","v3.1.7","v3.1.8","v3.1.9","v3.1.10","v3.1.11","develop"]
        utplsql_file: ["utPLSQL"]
        jdk: ['8']
        include:
          - utplsql_version: "v3.0.0"
            jdk: '8'
            utplsql_file: "utPLSQLv3.0.0"
    services:
      oracle:
        image: gvenzl/oracle-xe:18.4.0-slim
        env:
          ORACLE_PASSWORD: oracle
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --name oracle

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{matrix.jdk}}

      - name: Install utplsql
        run:  .travis/install_utplsql.sh

      - name: Install demo project
        run:  .travis/install_demo_project.sh

      - name: Build and Test
        run:  mvn verify jar:jar appassembler:assemble

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          name: 'Github Actions[bot]'
          icon_url: 'https://octodex.github.com/images/mona-the-rivetertocat.png'
