name: Release

on:
  push:
    tags:
      - "*.*.*"

  workflow_dispatch:

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Build Release
        run: mvn package appassembler:assemble assembly:single -DskipTests

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/utPLSQL-cli.zip

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          name: 'Github Actions[bot]'
          icon_url: 'https://octodex.github.com/images/mona-the-rivetertocat.png'
