name: Release

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build Release
        run: mvn package appassembler:assemble assembly:single checksum:files -DskipTests

      - name: Release
        uses: softprops/action-gh-release@v2.6
        with:
          files: |
            target/utPLSQL-cli.zip
            target/utPLSQL-cli.zip.md5
